package com.example.example

import com.google.gson.annotations.SerializedName


data class BasketList (

    @SerializedName("id"                           ) var id                        : Int?,
    @SerializedName("code"                         ) var code                      : String?,
    @SerializedName("bond_category_id"             ) var bondCategoryId            : Int? ,
    @SerializedName("isin"                         ) var isin                      : String?,
    @SerializedName("name"                         ) var name                      : String?,
    @SerializedName("display_name"                 ) var displayName               : String?,
    @SerializedName("coupon_rate"                  ) var couponRate                : Double?,
    @SerializedName("yield_to_maturity"            ) var yieldToMaturity           : Double?,
    @SerializedName("is_perpetual"                 ) var isPerpetual               : Int? ,
    @SerializedName("issue_date"                   ) var issueDate                 : String?,
    @SerializedName("listed_date"                  ) var listedDate                : String?,
    @SerializedName("maturity_date"                ) var maturityDate              : String?,
    @SerializedName("current_trade_yield_nse"      ) var currentTradeYieldNse      : Double?,
    @SerializedName("current_price_nse"            ) var currentPriceNse           : Int?,
    @SerializedName("current_variance_price_nse"   ) var currentVariancePriceNse   : String?,
    @SerializedName("current_trade_yield_bse"      ) var currentTradeYieldBse      : Double?,
    @SerializedName("current_price_bse"            ) var currentPriceBse           : Int?,
    @SerializedName("current_variance_price_bse"   ) var currentVariancePriceBse   : String?,
    @SerializedName("current_trade_yield_neo"      ) var currentTradeYieldNeo      : String?,
    @SerializedName("current_price_neo"            ) var currentPriceNeo           : String?,
    @SerializedName("current_variance_price_neo"   ) var currentVariancePriceNeo   : String?,
    @SerializedName("face_value"                   ) var faceValue                 : Int?,
    @SerializedName("taxation"                     ) var taxation                  : String?,
    @SerializedName("is_taxable"                   ) var isTaxable                 : Int?,
    @SerializedName("issuer_id"                    ) var issuerId                  : Int?,
    @SerializedName("seniority_id"                 ) var seniorityId               : Int?,
    @SerializedName("highlights"                   ) var highlights                : String?,
    @SerializedName("is_listed"                    ) var isListed                  : Int?,
    @SerializedName("interest_payment_type_id"     ) var interestPaymentTypeId     : Int?,
    @SerializedName("interest_payout_frequency_id" ) var interestPayoutFrequencyId : Int?,
    @SerializedName("put_date"                     ) var putDate                   : String?,
    @SerializedName("call_date"                    ) var callDate                  : String?,
    @SerializedName("is_nri_eligible"              ) var isNriEligible             : Int?,
    @SerializedName("logo_url"                     ) var logoUrl                   : String?,
    @SerializedName("logo_s3_key"                  ) var logoS3Key                 : String?,
    @SerializedName("logo_s3_bucket"               ) var logoS3Bucket              : String?,
    @SerializedName("status"                       ) var status                    : String?,
    @SerializedName("mode_of_issue_id"             ) var modeOfIssueId             : String?,
    @SerializedName("approved_by"                  ) var approvedBy                : String?,
    @SerializedName("approved_at"                  ) var approvedAt                : String?,
    @SerializedName("remark"                       ) var remark                    : String?,
    @SerializedName("created_by"                   ) var createdBy                 : String?,
    @SerializedName("last_updated_by"              ) var lastUpdatedBy             : String?,
    @SerializedName("meta"                         ) var meta                      : String?,
    @SerializedName("is_active"                    ) var isActive                  : Int?,
    @SerializedName("created_at"                   ) var createdAt                 : String?,
    @SerializedName("updated_at"                   ) var updatedAt                 : String?,
    @SerializedName("type_of_issuer"               ) var typeOfIssuer              : String?,
    @SerializedName("issuer_name"                  ) var issuerName                : String?,
    @SerializedName("industry"                     ) var industry                  : String?,
    @SerializedName("head_office"                  ) var headOffice                : String?,
    @SerializedName("business_sector"              ) var businessSector            : String?,
    @SerializedName("ownership"                    ) var ownership                 : String?,
    @SerializedName("year_founded"                 ) var yearFounded               : String?,
    @SerializedName("owner"                        ) var owner                     : String?,
    @SerializedName("issuer_highlights"            ) var issuerHighlights          : String?,
    @SerializedName("categoryname"                 ) var categoryname              : String?,
    @SerializedName("rating"                       ) var rating                    : String?,
    @SerializedName("ratingagencyname"             ) var ratingagencyname          : String?,
    @SerializedName("paymenttype"                  ) var paymenttype               : String?,
    @SerializedName("paymentfrequency"             ) var paymentfrequency          : String?

)